var dude;
var background;
var girlHead;
var spaceBar;
var isLooking = false;
var isLookingAway = false;
var timerBox;
var meterBox;
var meterValue;
var timerValue;
var startButton;
var startGame = false;
var timerInterval=0;
var timerText;
var ogleSlide;
var ogleSlider;
