var dude;
var background;
var girlHead;
var spaceBar;
var isLooking = false;
var isLookingAway = false;
var timerBox;
var meterBox;
var meterValue;
var timerValue;
var startButton;
var startGame = false;
var timerInterval=0;
var timerText;
var ogleSlide;
var ogleSlider;
var ogleValue=0;
var girlHeadPosition = 1;
var girlHeadGazeTimer = 0;
var girlScanning = true;
var girlGazing = false;
var girlHeadNextPosition = 1;
var girlGazeLength = 100;
var slider;
var wonText;
var timesUpText;
var girlTurn;
var music;
var hey;
var timesUp;
var uhOh;
var busted;
var yay;
var tenSeconds;
var bustedText;
